

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/ecommerce_db?allowPublicKeyRetrieval=true&useSSL=false
    password: 123456
    username: root
  jpa:
    database-platform: org.springframework.orm.jpa.vendor.Database.MYSQL
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globaly_quoted_identifiers: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
server:
  port: 8099
